apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: development-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: django-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
### SERVICES ###
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: development-app
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  # untuk LoadBalancer
  # type: LoadBalancer
  # untuk NodePort
  type: NodePort
  ### END SERVICES ###
